# Generated by Django 4.2.28 on 2026-02-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50, verbose_name='姓名')),
                ('employee_id', models.CharField(max_length=50, verbose_name='工号')),
                ('start_datetime', models.DateTimeField(verbose_name='加班开始时间')),
                ('end_datetime', models.DateTimeField(verbose_name='加班结束时间')),
                ('include_lunch_break', models.BooleanField(default=False, verbose_name='包含午休 12:00-13:30')),
                ('include_evening_break', models.BooleanField(default=False, verbose_name='包含晚间休息 17:00-17:30')),
                ('reason', models.TextField(blank=True, verbose_name='加班原因')),
                ('region', models.CharField(choices=[('shanghai', '上海'), ('beijing', '北京'), ('chengdu', '成都'), ('other', '其他')], default='shanghai', max_length=20, verbose_name='地域')),
                ('manager', models.CharField(max_length=50, verbose_name='主管')),
                ('overtime_hours', models.DecimalField(decimal_places=2, editable=False, max_digits=5, verbose_name='加班时长（小时）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '加班记录',
                'verbose_name_plural': '加班记录',
                'ordering': ['-start_datetime', 'employee_name'],
            },
        ),
    ]
