# Generated by Django 4.2.28 on 2026-02-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimerecord',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='冻结后只能在后台解除，前台无法再编辑。', verbose_name='已冻结，不可再修改'),
        ),
        migrations.AlterField(
            model_name='overtimerecord',
            name='include_evening_break',
            field=models.BooleanField(default=False, verbose_name='跨晚间时段时扣除 17:00-17:30'),
        ),
        migrations.AlterField(
            model_name='overtimerecord',
            name='include_lunch_break',
            field=models.BooleanField(default=False, verbose_name='跨午休时段时扣除 12:00-13:30'),
        ),
    ]
