# Generated by Django 4.2.28 on 2026-02-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0002_overtimerecord_is_locked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimerecord',
            name='region',
            field=models.CharField(choices=[('xian', '西安'), ('shanghai', '上海'), ('beijing', '北京')], default='xian', max_length=20, verbose_name='地域'),
        ),
    ]
