# Generated by Django 4.2.28 on 2026-02-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0003_alter_overtimerecord_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='主管姓名')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '主管选项',
                'verbose_name_plural': '主管选项',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RegionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='地域名称')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '地域选项',
                'verbose_name_plural': '地域选项',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AlterField(
            model_name='overtimerecord',
            name='manager',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='主管'),
        ),
        migrations.AlterField(
            model_name='overtimerecord',
            name='region',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='地域'),
        ),
    ]
