# Generated by Django 4.2.28 on 2026-02-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0004_manageroption_regionoption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(help_text='支持多行，可写规则说明。', verbose_name='内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否展示')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '公告/规则',
                'verbose_name_plural': '公告/规则',
                'ordering': ('order', '-updated_at'),
            },
        ),
    ]
