# Generated by Django 4.2.28 on 2026-02-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0005_add_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如：春节假期、2月第1个周末', max_length=100, verbose_name='时段名称')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '假期/时段',
                'verbose_name_plural': '假期/时段',
                'ordering': ('start_date', 'order'),
            },
        ),
    ]
