# Generated by Django 4.2.28 on 2026-02-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0006_add_holiday_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='部门名称')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '部门选项',
                'verbose_name_plural': '部门选项',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='overtimerecord',
            name='department',
            field=models.CharField(blank=True, default='高斯实验室', max_length=50, verbose_name='部门'),
        ),
    ]
