# Generated by Django 4.2.28 on 2026-03-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0007_add_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionoption',
            name='evening_end',
            field=models.TimeField(blank=True, null=True, verbose_name='晚间休息结束'),
        ),
        migrations.AddField(
            model_name='regionoption',
            name='evening_start',
            field=models.TimeField(blank=True, null=True, verbose_name='晚间休息开始'),
        ),
        migrations.AddField(
            model_name='regionoption',
            name='lunch_end',
            field=models.TimeField(blank=True, null=True, verbose_name='午休结束'),
        ),
        migrations.AddField(
            model_name='regionoption',
            name='lunch_start',
            field=models.TimeField(blank=True, null=True, verbose_name='午休开始'),
        ),
        migrations.AlterField(
            model_name='overtimerecord',
            name='include_evening_break',
            field=models.BooleanField(default=False, verbose_name='跨晚间时段时扣除（时间按地域）'),
        ),
        migrations.AlterField(
            model_name='overtimerecord',
            name='include_lunch_break',
            field=models.BooleanField(default=False, verbose_name='跨午休时段时扣除（时间按地域）'),
        ),
    ]
