# Generated by Django 4.2.28 on 2026-03-03 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0008_region_break_times'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, help_text='如：2025年春节加班统一审批邮件', max_length=200, verbose_name='备注')),
                ('attachment', models.FileField(upload_to='overtime_approvals/batch/%Y/%m/', verbose_name='邮件附件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '统一审批邮件批次',
                'verbose_name_plural': '统一审批邮件批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='overtimerecord',
            name='approval_attachment',
            field=models.FileField(blank=True, null=True, upload_to='overtime_approvals/personal/%Y/%m/', verbose_name='审批邮件附件'),
        ),
        migrations.AddField(
            model_name='overtimerecord',
            name='email_status',
            field=models.CharField(choices=[('pending', '未发邮件'), ('unified', '已统一发邮件'), ('personal', '已个人补发邮件')], default='pending', max_length=20, verbose_name='邮件状态'),
        ),
        migrations.AddField(
            model_name='overtimerecord',
            name='approval_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='overtime.approvalbatch', verbose_name='统一审批批次'),
        ),
    ]
